### ISSUE TITLE
How to createp2sh

### ISSUE THREAD

**Issue by emmnx** [bip32JP/bip32JP.github.io#10]
Hi, man. First of all, thanks for your work.

Newbie here, I am struggling right now to use your tool, [createp2sh](http://bip32jp.github.io/english/createp2sh.html), trying to understand how it works.

So, basically, "Enter redeem script" is for the redeem script, clear, "Send to?" is for the address, but "Enter scriptSig (solution)" is not clear to me, I've tried with the Hash160 of the redeem script address, but it's not getting me any coins, of course.

How do you know what to put in that second field? ("Enter scriptSig")

Thanks again.

**Comment by dabura667** [comment]
eg: basically, scriptSig is the ops and pushes that will be done before pushing the redeemscript.

ie. this screen + "Send Bitcoin" button

![_003](https://user-images.githubusercontent.com/6586275/43988344-be7e74d0-9d6e-11e8-9aa2-9c441cea8a4c.png)

Made this transaction:

https://testnet.smartbit.com.au/tx/dbb29855e2e6c9c051f14699802d0e4627fdbaf189db75b9f684f7d822be976f

(You can see the scriptSig if you click the show source button `</>` to see all the data in the transaction)

**Comment by dabura667** [comment]
You can also use SIG_x to represent signatures if you want multiple signatures, SIG_1 SIG_2 etc etc. each will have a new place to enter the private key for the signatures.

![_004](https://user-images.githubusercontent.com/6586275/43988446-5fbc080c-9d70-11e8-8d17-b3cb828f92ae.png)

This resulted in this transaction:

https://testnet.smartbit.com.au/tx/4016ecc801b1ee1836679eb569b34c4aa4b86d88f508e65d6b5b56d45065a6de

**Comment by dabura667** [comment]
This tool is meant to teach people how bitcoin Script language and its OP codes work.

Do not put money in this.

**Comment by emmnx** [comment]
It looks like there is no way to include nLocktime to the transaction. It is required for CLTV transactions, if I'm not mistaken.

**Comment by dabura667** [comment]
@emmnx yes. There is no way to include nLocktime or modify nSequence of the inputs.

That is outside the scope of this tool... however it should be easy to modify to fit your needs.

**Comment by emmnx** [comment]
Thanks a lot, anyway, this is a great tool!
