### ISSUE TITLE
Help me please I forgot seed , and passwords but I have Json file please help me please

### ISSUE THREAD

**Issue by cindezii** [bip32JP/bip32JP.github.io#14]
I need help ​I forgot my seed and password right now I'm really worried. I don't know which way to turn. Contact Support metamesk. No response. I'm helpless

**Comment by junderw** [comment]
> ​I forgot my seed and password

If you have completely forgotten both of these, there is zero chance of recovering your funds. No one can help you... sorry.

**Comment by cindezii** [comment]
If I have a json file, is there any proof of transfer from binance, is there a way to get it back?

**Comment by junderw** [comment]
This is not Binance support. Sorry.
