### ISSUE TITLE
QR codes in multiple addresses

### ISSUE THREAD

**Issue by BrunoAP1981** [bip32JP/bip32JP.github.io#7]
Hello guys!

First of all, nice work!

I write this to ask you to create QR codes aside generation of various addresses (private and public), not just for one only, if it is possible, of course.

One cool thing also would be adding a feature that scrambles and create random addresses like bitaddress.org (by randomly moving a mouse or typing keyboard letters).

Once again, thank you very much for your work!  
Regards.
Bruno

**Comment by dabura667** [comment]
1. Adding a QR for private key would be easy, one line of code.
2. The site already uses mouse and keyboard input to generate randomness. But unlike bitaddress it does not stop you. So if you move your mouse around for 5 seconds before clicking “generate new” you should have extra randomness.

**Comment by BrunoAP1981** [comment]
Hey!

In 2., does this work for multiple addresses or just for one?

Thank you very much for your work!

Em 14 de out de 2017 22:10, "Dabura667" <notifications@github.com> escreveu:

**Comment by dabura667** [comment]
> In 2., does this work for multiple addresses or just for one?

Your question makes no sense. Have you even used this tool before?

It's impossible to make "just one address" with this tool. It's a tool for making HD wallets (wallets with infinite addresses)

I repeat, your question makes no sense.

The mouse and keyboard movements are constantly concatenated and hashed, then stored in a hidden html element for later hashing, every time you move your mouse more then 10 pixels or hit any key. The keys themselves are not recorded, their codes are concatenated to the current state and hashed again to replace the state of the hash.

**Comment by BrunoAP1981** [comment]
Hey,

I'm sorry, what i've meant is when you generate various pairs  (public and
private) we'd have the same scramble mechanism of just one pair creation?

I'm not a programmer... May i sugest a sentence informing users of that
scrambling fraturei and how to do this (as you explainned in this chat)?

Regards

Em 15 de out de 2017 13:48, "Dabura667" <notifications@github.com> escreveu:
