### ISSUE TITLE
https://github.com/bip32JP/bip32JP.github.io

### ISSUE THREAD

**Issue by young1221** [bip32JP/bip32JP.github.io#8]
Mnemonic Code Converter

**Comment by dabura667** [comment]
What is your issue?

**Comment by calhroub** [comment]
Hi. Is it possible to use this tool to find my multi-sig private key? I tried derivation paths:
m/44'/0'/0'/0/0
m/44'/0'/0'/0/1
m/44'/0'/0'/0/2
m/44'/0'/0'/0/3
m/44'/0'/0'/0/4
But it keeps showing me non multi-sig addresses. My bitcoin has been stuck in Dark Wallet for a while and I haven't been able to find a solution...
Any help would be greatly appreciated
